spring.application.name=coupons

# ===============================
# = DATA SOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/coupons
spring.datasource.username=--------
spring.datasource.password=-------

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# = TRANSAKCJE
# ===============================
spring.jpa.open-in-view=false

# ===============================
# = LOGGING
# ===============================
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO


# ===============================
# = GEO API
# ===============================
geo.api.url=https://ipapi.co
